deployIp: 172.21.213.86
spring:
  data:
    mongodb:
      host: ${deployIp}
      port: 27017
      authentication-database: admin
      database: dsc
      username: yzwang
      password: wyz980903

jks_path: ${JKS_PATH}
