deploy_ip: 172.21.212.79

spring:
  data:
    mongodb:
      #      host: 119.45.181.127   # 腾讯云
      host: ${deploy_ip}   # opengms组内服务器
      port: 27017
      authentication-database: admin
      database: dsc
      username: yzwang
      password: wyz980903