spring:
  profiles:
    active: dev


jwt:
  publicKey: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiluRji4NLXRxoyQsYH2Y1jGSjx9U22rX6sVe7Kvsw2Og7Ndhbwu/BbGW34xqoB5LL+99fT70LT14TCvRxVn4MnUyguH0WMlMklGOosGxjkRaXxovJaDW8tm2SN05C3bXn+/SBXsD5LIqhSjdbJxA6aEUXu8qFqQjhe2vMzwup/0XHxtyfHTfY3azEaFTzlfem88acHFkr5HtiJrXj0SdxxNehf0ylr+vLYQUjnww8RtJ7voTZIrtQqbXJIlcJ1puZGJOE6AuHVZtpcZoeJYFjEHR9CucFgjtkEUiyilKee3k2qPxaTnBsPCXon1jWcKoP9MFTVsvG5B8ipFQRRxyHwIDAQAB-----END PUBLIC KEY-----