spring:
  data:
    mongodb:
      host: mongo-db
      port: 27017
      authentication-database: admin
      database: dsc
      username: ${MONGO_INITDB_ROOT_USERNAME:dsc}
      password: ${MONGO_INITDB_ROOT_PASSWORD:dsc123}

jks_path: ${JKS_PATH}
