spring:
  redis:
    host: redis-cache
    port: 6379
    password: dsc123
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
    timeout: 1000
  cloud:
    gateway:
      routes:
        - id: dsc-systemMS
          uri: http://system-core:7890/
          predicates:
            - Path=/dsc-systemMS/**
        - id: dsc-auth-central
          uri: http://auth-central:9400/
          predicates:
            - Path=/dsc-auth-central/**
        - id: dsc-ws
          uri: ws://system-core:7890/
          predicates:
            - Path=/dsc-systemMS/webSocket/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://auth-central:9400/dsc-auth-central/rsa/publicKey'
secure:
  ignore:
    urls: #配置白名单路径，更新白名单必须重启网关服务，否则不生效！
      - "/actuator/**"
      - "/dsc-auth-central/oauth/token"
      - "/dsc-auth-central/oauth/check_token"
      - "/dsc-systemMS/dsc-user/register"
      - "/dsc-systemMS/dsc-user/login"
      - "/dsc-systemMS/dsc-user/resetPassword/**"
      - "/dsc-systemMS/static/**"
      - "/dsc-systemMS/dsc-user/active/**"
      - "/dsc-systemMS/dsc-vector-service/getMvt/**"
      - "/dsc-systemMS/webSocket/**"
      # - "/dsc-systemMS/dsc-file-uploader/**"