deployIp: 172.21.212.177        #部署要改
frontendIp: 172.21.212.177:9192        #部署要改
#deployIp: 119.45.181.127       #部署要改

spring:
  web:
    resources:
      static-locations: classpath:/resources/, classpath:/static/
  servlet:
    multipart:
      max-file-size: 2048MB     #单文件不超过2G
      max-request-size: 5120MB    #所有文件不超过5G
  data:
    mongodb:
      host: mongo-db
      port: 27017
      authentication-database: admin
      database: dsc
      username: dsc
      password: dsc123
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/dsc_postdb
    username: postgres
    password: dsc123
    hikari:
      connection-timeout: 60000
  mail:
    host: smtp.qq.com
    protocol: smtps
    username: 2740962735@qq.com
    from: 2740962735@qq.com
    password: ktllrsdzptdfdfed
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:                          #redis存jwt黑名单
    host: redis-cache
    port: 6379
    password: dsc123
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
    timeout: 1000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**

mvt_url: ${MVT_SOURCE_URL:http://localhost:9527}
gateway_addr: http://gateway:9527
frontend_url: ${APP_SOURCE_URL:http://localhost:9192}/home/activateresult/{0}
user_active_url: /dsc-systemMS/dsc-user/active/{0}
fileSavePath: /home/minio-data/
fileTempPath: /home/temp
fileSavePathWin: ${MINIO_HOME:C:\Users\Administrator\Documents\minio-data}\data\
fileTempPathWin: ${MINIO_HOME:C:\Users\Administrator\Documents\minio-data}\temp\
scriptPath: /home/script/
shp2pgsql: shp2pgsql -I -s {0} -W {1} {2} {3} | psql -h postgres-db -p 5432 -U postgres -d dsc_postdb
shp2pgsqlWin: ${PG_HOME:C:\Program Files (x86)\PostgreSQL\12\bin}\shp2pgsql.exe -I -s {0} -W {1} {2} {3} | ${PG_HOME:C:\Program Files (x86)\PostgreSQL\12\bin}\psql.exe -h ${deployIp} -p 5432 -U postgres -d dsc_postdb
pg_password: ${PG_PASSWORD:dsc123}

# docker相关
docker:
  docker_url: ${DOCKER_URL}
  docker_tls_verify: ${DOCKER_TLS_VERIFY:no}
  docker_cert_path: ${DOCKER_CERT_PATH:none}
  docker_api_version: ${DOCKER_API_VERSION}

minioEndpoint: http://124.70.17.22

minio:
  endpoint: ${MINIO_API_URL:http://124.70.17.22}
  accessKey: dsc
  secretKey: dsc123456
  bucketName: dsc-file
  sceneThumbnailsBucket: scene-thumbnails
  avatarBucket: avatar
  gaOutputBucket: dsc-ga-output
  pyFilesBucket: py-files