deployIp: 172.21.213.86
frontendIp: 172.21.213.86
#deployIp: 119.45.181.127
whiteboxDockerServer: 172.21.213.212

spring:
  web:
    resources:
      static-locations: classpath:/resources/, classpath:/static/
  servlet:
    multipart:
      max-file-size: 2048MB     #单文件不超过2G
      max-request-size: 5120MB    #所有文件不超过5G
  data:
    mongodb:
      host: ${deployIp}
      port: 27017
      authentication-database: admin
      database: dsc
      username: yzwang
      password: wyz980903
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${deployIp}:5432/dsc_postdb
    username: postgres
    password: wyz980903
    hikari:
      connection-timeout: 60000
  mail:
    host: smtp.qq.com
    username: 2740962735@qq.com
    from: 2740962735@qq.com
    password: ktllrsdzptdfdfed
  redis:                          #redis存jwt黑名单
    host: ${deployIp}
    port: 6379
    password: ninja980903
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
    timeout: 1000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**


gateway_addr: http://${deployIp}:9527
frontend_url: http://${frontendIp}/home/activateresult/{0}
user_active_url: /dsc-systemMS/dsc-user/active/{0}
fileSavePath: /home/minio-data/
unzipTempPath: /home/temp/{0}
fileSavePathWin: ${MINIO_HOME:C:\Users\Administrator\Documents\minio-data}\data\
unzipTempPathWin: ${MINIO_HOME:C:\Users\Administrator\Documents\minio-data}\temp\{0}
shp2pgsql: shp2pgsql -I -s {0} -W {1} {2} {3} | psql -h ${deployIp} -p 5432 -U postgres -d dsc_postdb
shp2pgsqlWin: ${PG_HOME:C:\Program Files (x86)\PostgreSQL\12\bin}\shp2pgsql.exe -I -s {0} -W {1} {2} {3} | ${PG_HOME:C:\Program Files (x86)\PostgreSQL\12\bin}\psql.exe -h ${deployIp} -p 5432 -U postgres -d dsc_postdb
pg_password: wyz980903

# docker相关
DOCKER:
  DOCKER_HOST: tcp://${deployIp}:2375
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: /home/user/.docker/certs
  DOCKER_CONFIG: /home/user/.docker
  api:
    version: 1.23
  registry:
    url: https://index.docker.io/v1/
    username: dockeruser
    password: ilovedocker
    email: dockeruser@github.com


minio:
  endpoint: http://${deployIp}:9000
  accessKey: yzwang
  secretKey: wyz980903
  bucketName: dsc-file
  sceneThumbnailsBucket: scene-thumbnails
  avatarBucket: avatar
  gaOutputBucket: dsc-ga-output
  pyFilesBucket: py-files