deployIp: 172.21.213.86
frontendIp: localhost:8889/dsc-app
sagaDockerServer: 119.45.181.127/dsc-wps/       #部署要改
pythonDockerServer: 172.21.213.86        #部署要改
dockerCert: D:/docker-2375-cert

spring:
  web:
    resources:
      static-locations: classpath:/resources/, classpath:/static/
  servlet:
    multipart:
      max-file-size: 2048MB     #单文件不超过2G
      max-request-size: 5120MB    #所有文件不超过5G
  data:
    mongodb:
      host: ${deployIp}
      port: 17016
      authentication-database: admin
      database: dsc
      username: dsc
      password: dsc123
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${deployIp}:15431/dsc_postdb
    username: dsc
    password: dsc123
  mail:
    host: smtp.qq.com
    username: 2740962735@qq.com
    from: 2740962735@qq.com
    password: uxkmfprmynvhdeai
  redis:                          #redis存jwt黑名单
    host: ${deployIp}
    port: 16378
#    password: ninja980903
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
    timeout: 1000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**

mvt_url: ${MVT_SOURCE_URL:http://localhost:9527}
gateway_addr: http://localhost:9527   # gateway
frontend_url: http://${frontendIp}/home/activateresult/{0}
user_active_url: /dsc-systemMS/dsc-user/active/{0}
fileSavePath: F:\dsc\dsc-minio\data
fileTempPath: F:\dsc\dsc-minio\temp
fileSavePathWin: ${MINIO_HOME:F:\dsc\dsc-minio}\data
fileTempPathWin: ${MINIO_HOME:F:\dsc\dsc-minio}\temp\{0}
scriptPath: /home/script/
shp2pgsql: shp2pgsql -I -s {0} -W {1} {2} {3} | psql -h ${deployIp} -p 15431 -U postgres -d dsc_postdb
shp2pgsqlWin: ${PG_HOME:D:\majorSoftware\PostgreSQL\10\bin}\shp2pgsql.exe -I -s {0} -W {1} {2} {3} | ${PG_HOME:D:\majorSoftware\PostgreSQL\10\bin}\psql.exe -h ${deployIp} -p 15431 -U postgres -d dsc_postdb
pg_password: dsc123

docker:
  docker_url: ${DOCKER_URL:119.45.181.127:2375}
  docker_tls_verify: ${DOCKER_TLS_VERIFY:yes}
  docker_cert_path: ${DOCKER_CERT_PATH:D:\\docker-2375-cert\\}
  docker_api_version: ${DOCKER_API_VERSION:1.43}



minio:
  endpoint: http://124.70.17.22
  accessKey: dsc
  secretKey: dsc123456
  bucketName: dsc-file
  sceneThumbnailsBucket: scene-thumbnails
  avatarBucket: avatar
  gaOutputBucket: dsc-ga-output
  pyFilesBucket: py-files